# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qqgroup',
            name='members',
            field=models.ManyToManyField(blank=True, to='bbs.UserProfile'),
        ),
    ]
