# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_chat', '0002_auto_20170610_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=22)),
                ('password', models.CharField(max_length=33)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=22)),
                ('content', models.CharField(max_length=33)),
            ],
        ),
        migrations.AddField(
            model_name='favor',
            name='new_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_chat.News'),
        ),
        migrations.AddField(
            model_name='favor',
            name='user_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_chat.MyUser'),
        ),
    ]
