# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-03 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=64, unique=True)),
                ('key', models.TextField()),
                ('status', models.SmallIntegerField(choices=[(0, 'Waiting'), (1, 'Accepted'), (2, 'Rejected')], default=0)),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='hosts',
            field=models.ManyToManyField(blank=True, to='Arya.Host'),
        ),
    ]
