# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-03 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arya', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='os_type',
            field=models.CharField(choices=[('redhat', 'Redhat\\CentOS'), ('ubuntu', 'Ubuntu'), ('suse', 'Suse'), ('windows', 'Windows')], default='redhat', max_length=32),
        ),
    ]
